sudo: required
dist: trusty
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
      - libsfml-dev
      - libxml2-utils
env:
  - CTEST_OUTPUT_ON_FAILURE=1
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest
  - xmllint --schema level.xsd level.xml
